insert into Sucursal (Id_Sucursal, Calle, Numero, Colonia, Municipio, Estado, Pais) values (1, 'Cristobal Colon' , 2523, 'Paolo A. de la Garza' , 'Monterrey' , 'Nuevo Leon' , 'Mexico');
insert into Sucursal (Id_Sucursal, Calle, Numero, Colonia, Municipio, Estado, Pais) values (2, 'Bernardo Reyes' , 3403, 'Hidalgo', 'Monterrey' , 'Nuevo Leon', 'Mexico');
insert into Sucursal (Id_Sucursal, Calle, Numero, Colonia, Municipio, Estado, Pais) values (3, 'Revolucion Mexicana', 60, 'Ejidal', 'Guadalupe', 'Zacatecas', 'Mexico');
insert into Sucursal (Id_Sucursal, Calle, Numero, Colonia, Municipio, Estado, Pais) values (4, 'Morenita Mia' , 331, 'San Bartolo', 'San Nicolas de los Garza', 'Nuevo Leon', 'Mexico');
insert into Sucursal (Id_Sucursal, Calle, Numero, Colonia, Municipio, Estado, Pais) values (5, 'Diego Diaz de Berlanga' , 203, 'Valle del Nogalar', 'San Nicolas de los Garza', 'Nuevo Leon', 'Mexico');
insert into Sucursal (Id_Sucursal, Calle, Numero, Colonia, Municipio, Estado, Pais) values (6, 'Agustin Melgar' , 2328, 'Reforma', 'Monterrey', 'Nuevo Leon', 'Mexico');
insert into Sucursal (Id_Sucursal, Calle, Numero, Colonia, Municipio, Estado, Pais) values (7, 'Cristobal Colon' , 301, 'Independencia', 'Coatzacalcos', 'Veracruz', 'Mexico');
insert into Sucursal (Id_Sucursal, Calle, Numero, Colonia, Municipio, Estado, Pais) values (8, 'Zarco' , 6, 'San Simon', 'Tolnahuac', 'CDMX', 'Mexico');
insert into Sucursal (Id_Sucursal, Calle, Numero, Colonia, Municipio, Estado, Pais) values (9, 'Rio Rhin' , 1054, 'Quinta Velare', 'Guadalajara', 'Jalisco', 'Mexico');
insert into Sucursal (Id_Sucursal, Calle, Numero, Colonia, Municipio, Estado, Pais) values (10, 'Blv Jose Ma. Morelos' , 1116, 'Real de San Jose', 'Leon', 'Guanajuato', 'Mexico');
insert into Sucursal (Id_Sucursal, Calle, Numero, Colonia, Municipio, Estado, Pais) values (11, 'Blv PLan de Gpe' , 712, 'Centro', 'Ramos Arispe', 'Coahuila', 'Mexico');
insert into Sucursal (Id_Sucursal, Calle, Numero, Colonia, Municipio, Estado, Pais) values (12, 'Gonzales Cossio' , 3909, 'Bosque Real', 'Chihuahua', 'Chihuahua', 'Mexico');
insert into Sucursal (Id_Sucursal, Calle, Numero, Colonia, Municipio, Estado, Pais) values (13, 'Priv de David Alfaros Siqueiros' , 3210, 'Ampliacion Crucero', 'Chihuahua', 'Chihuahua', 'Mexico');
insert into Sucursal (Id_Sucursal, Calle, Numero, Colonia, Municipio, Estado, Pais) values (14, 'Cristobal Colon' , 301, 'Independencia', 'Coatzacalcos', 'Veracruz', 'Mexico');
insert into Sucursal (Id_Sucursal, Calle, Numero, Colonia, Municipio, Estado, Pais) values (15, 'Santo Domingo' , 1051, 'Valle de Santo Domingo', 'Monterrey', 'Nuevo Leon', 'Mexico');
insert into Sucursal (Id_Sucursal, Calle, Numero, Colonia, Municipio, Estado, Pais) values (16, 'Calzada la Huerta' , 729, 'Morelos', 'Morelia', 'Michoacan', 'Mexico');
insert into Sucursal (Id_Sucursal, Calle, Numero, Colonia, Municipio, Estado, Pais) values (17, 'Pasteur' , 412, 'Valle Alameda', 'Queretaro', 'Queretaro', 'Mexico');
insert into Sucursal (Id_Sucursal, Calle, Numero, Colonia, Municipio, Estado, Pais) values (18, 'Santo Domingo' , 1501, 'Valle de Santo Domingo', 'Monterrey', 'Nuevo Leon', 'Mexico');
insert into Sucursal (Id_Sucursal, Calle, Numero, Colonia, Municipio, Estado, Pais) values (19, 'Doctor Liceaga' , 113, 'Valle de Santo Domingo', 'Monterrey', 'Nuevo Leon', 'Mexico');
insert into Sucursal (Id_Sucursal, Calle, Numero, Colonia, Municipio, Estado, Pais) values (20, 'Mixtecas' , 107, 'Ajusco', 'CDMX', 'CDMX', 'Mexico');
insert into Sucursal (Id_Sucursal, Calle, Numero, Colonia, Municipio, Estado, Pais) values (21, 'Pino Suarez' , 214, '5 de Mayo', 'Toluca', 'Edo Mexico', 'Mexico');
insert into Sucursal (Id_Sucursal, Calle, Numero, Colonia, Municipio, Estado, Pais) values (22, 'Abeto' , 66, 'Los Olvera', 'Queretaro', 'Queretaro', 'Mexico');
insert into Sucursal (Id_Sucursal, Calle, Numero, Colonia, Municipio, Estado, Pais) values (23, 'Pico de la Malinche' , 600, 'Jardin de los Puentes', 'Monterrey', 'Nuevo Leon', 'Mexico');
insert into Sucursal (Id_Sucursal, Calle, Numero, Colonia, Municipio, Estado, Pais) values (24, 'Panamericana' , 606, 'Campestre Celaya', 'Celaya', 'Guanajuato', 'Mexico');
insert into Sucursal (Id_Sucursal, Calle, Numero, Colonia, Municipio, Estado, Pais) values (25, 'Carretera 30' , 220, 'Morelos', 'Monclova', 'Coahuila', 'Mexico');
insert into Sucursal (Id_Sucursal, Calle, Numero, Colonia, Municipio, Estado, Pais) values (26, 'Rtno 22' , 45, 'Avante', 'CDMX', 'CDMX', 'Mexico');
insert into Sucursal (Id_Sucursal, Calle, Numero, Colonia, Municipio, Estado, Pais) values (27, 'Agustin Melgar' , 13, 'San Bartolome', 'CDMX', 'CDMX', 'Mexico');
insert into Sucursal (Id_Sucursal, Calle, Numero, Colonia, Municipio, Estado, Pais) values (28, 'Miguel Hidalgo' , 144, 'Santa Maria Tomatlan', 'CDMX', 'CDMX', 'Mexico');
insert into Sucursal (Id_Sucursal, Calle, Numero, Colonia, Municipio, Estado, Pais) values (29, 'Miguel Nieto' , 2121, 'Industrial', 'Monterrey', 'Nuevo Leon', 'Mexico');
insert into Sucursal (Id_Sucursal, Calle, Numero, Colonia, Municipio, Estado, Pais) values (30, 'Pino Suarez' , 3026, 'Centro', 'Veracruz', 'Veracruz', 'Mexico');
	
